version: '3.8'

services:
  data-generator:
    container_name: data-generator
    build:
      context: datagenerator/
    restart: unless-stopped
    ports:
      - 8000:8080

  etl:
    container_name: etl
    env_file:
      - ./.env
    build:
      context: etl/
    restart: unless-stopped

  api:
    container_name: api
    env_file:
      - ./.env
    build:
      context: api/
    restart: unless-stopped
    ports:
      - 5000:5000
